import Navbar from "../components/navbar/Navbar";
import { Suspense } from "react";
export const metadata = {
  title: "IA Coworking",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <>
        <Navbar />
        {children}

    </>
  );
}
